const result ={
    "vskp": {
        "GIT": [
            [
                {
                    "company": "Fiat",
                    "profile_offered": "Graduate Engineer Trainee",
                    "Package(LPA)": 6,
                    "CSE": -1,
                    "IT": -1,
                    "ECE": 2,
                    "EEE": -1,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 2
                },
                {
                    "company": "Deloitte",
                    "profile_offered": "RFA/DAS/GDAS/CIA",
                    "Package(LPA)": 7.6,
                    "CSE": 41,
                    "IT": 1,
                    "ECE": 6,
                    "EEE": 0,
                    "Mech": 0,
                    "Civil": 0,
                    "BIO": 0,
                    "total_no_of_selections": 48
                },
                {
                    "company": "InfyTQ (Infosys)",
                    "profile_offered": "Systems Engineer",
                    "Package(LPA)": 3.36,
                    "CSE": 6,
                    "IT": 0,
                    "ECE": 0,
                    "EEE": 0,
                    "Mech": 0,
                    "Civil": 0,
                    "BIO": 0,
                    "total_no_of_selections": 6
                },
                {
                    "company": "Adobe (PPO)",
                    "profile_offered": "Software Development Engineer",
                    "Package(LPA)": 15.92,
                    "CSE": 1,
                    "IT": 0,
                    "ECE": 0,
                    "EEE": 0,
                    "Mech": 0,
                    "Civil": 0,
                    "BIO": 0,
                    "total_no_of_selections": 1
                },
                {
                    "company": "TCS Digital via Digital",
                    "profile_offered": "Systems Engineer",
                    "Package(LPA)": 7,
                    "CSE": 64,
                    "IT": 0,
                    "ECE": 9,
                    "EEE": 0,
                    "Mech": 0,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 73
                },
                {
                    "company": "TCS Ninja via Digital",
                    "profile_offered": "Assistant Systems Engineer",
                    "Package(LPA)": 3.36,
                    "CSE": 109,
                    "IT": 2,
                    "ECE": 18,
                    "EEE": 0,
                    "Mech": 0,
                    "Civil": 0,
                    "BIO": 0,
                    "total_no_of_selections": 129
                },
                {
                    "company": "Apisero",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": 5.1,
                    "CSE": 62,
                    "IT": 0,
                    "ECE": 12,
                    "EEE": -1,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 74
                },
                {
                    "company": "Infoview Systems",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": 3.5,
                    "CSE": 6,
                    "IT": 0,
                    "ECE": -1,
                    "EEE": -1,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 6
                },
                {
                    "company": "Cognizant GenC Next",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": 6.5,
                    "CSE": 16,
                    "IT": 0,
                    "ECE": 0,
                    "EEE": 0,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 16
                },
                {
                    "company": "Cognizant GenC Elevate via Next",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": 4.25,
                    "CSE": 21,
                    "IT": 0,
                    "ECE": 0,
                    "EEE": 0,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 21
                },
                {
                    "company": "Hexware",
                    "profile_offered": "PGET",
                    "Package(LPA)": 5,
                    "CSE": 2,
                    "IT": 0,
                    "ECE": 0,
                    "EEE": 0,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 2
                },
                {
                    "company": "Accolite",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": 6,
                    "CSE": 1,
                    "IT": -1,
                    "ECE": -1,
                    "EEE": -1,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 1
                },
                {
                    "company": "Accenture - ASE",
                    "profile_offered": "ASE",
                    "Package(LPA)": 4.5,
                    "CSE": 111,
                    "IT": 0,
                    "ECE": 15,
                    "EEE": 0,
                    "Mech": 1,
                    "Civil": 0,
                    "BIO": 1,
                    "total_no_of_selections": 128
                },
                {
                    "company": "Accenture - Advanced ASE",
                    "profile_offered": "Advanced ASE",
                    "Package(LPA)": 6.5,
                    "CSE": 33,
                    "IT": 0,
                    "ECE": 7,
                    "EEE": 0,
                    "Mech": 1,
                    "Civil": 0,
                    "BIO": 0,
                    "total_no_of_selections": 41
                },
                {
                    "company": "Josh Technology Group",
                    "profile_offered": "Software Engineer (Web/Mobile Technologies)",
                    "Package(LPA)": 9.65,
                    "CSE": 0,
                    "IT": 0,
                    "ECE": 0,
                    "EEE": -1,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 0
                },
                {
                    "company": "Optum - United Health Group",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": 7.15,
                    "CSE": 13,
                    "IT": 0,
                    "ECE": -1,
                    "EEE": -1,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 13
                },
                {
                    "company": "Tiger Analytics",
                    "profile_offered": "Analyst - Data Science",
                    "Package(LPA)": 7.5,
                    "CSE": 5,
                    "IT": 0,
                    "ECE": 0,
                    "EEE": 0,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 5
                },
                {
                    "company": "MuSigma",
                    "profile_offered": "Trainee Decision Scientist",
                    "Package(LPA)": 3,
                    "CSE": 55,
                    "IT": 0,
                    "ECE": 18,
                    "EEE": 0,
                    "Mech": 2,
                    "Civil": 0,
                    "BIO": 1,
                    "total_no_of_selections": 76
                },
                {
                    "company": "Keka",
                    "profile_offered": "Developer/Quality analyst",
                    "Package(LPA)": "6.00-7.00",
                    "CSE": 6,
                    "IT": 0,
                    "ECE": 3,
                    "EEE": 0,
                    "Mech": 0,
                    "Civil": 0,
                    "BIO": 0,
                    "total_no_of_selections": 9
                },
                {
                    "company": "Mindtree",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": 4,
                    "CSE": 28,
                    "IT": 0,
                    "ECE": 7,
                    "EEE": 0,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 35
                },
                {
                    "company": "Enquero (PPO)",
                    "profile_offered": "PPO",
                    "Package(LPA)": 6,
                    "CSE": 1,
                    "IT": -1,
                    "ECE": -1,
                    "EEE": -1,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 1
                },
                {
                    "company": "Cognizant GenC Elevate",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": 4.25,
                    "CSE": 42,
                    "IT": 0,
                    "ECE": 4,
                    "EEE": -1,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 46
                },
                {
                    "company": "Cognizant GenC",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": 4,
                    "CSE": 140,
                    "IT": 1,
                    "ECE": 48,
                    "EEE": 0,
                    "Mech": 9,
                    "Civil": 0,
                    "BIO": 0,
                    "total_no_of_selections": 198
                },
                {
                    "company": "Accelerize 360",
                    "profile_offered": "Saflesforce Developer",
                    "Package(LPA)": 7,
                    "CSE": 0,
                    "IT": -1,
                    "ECE": -1,
                    "EEE": -1,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 0
                },
                {
                    "company": "Wipro Elite",
                    "profile_offered": "Project Engineer",
                    "Package(LPA)": 3.5,
                    "CSE": 99,
                    "IT": 1,
                    "ECE": 31,
                    "EEE": 0,
                    "Mech": 5,
                    "Civil": 0,
                    "BIO": 1,
                    "total_no_of_selections": 137
                },
                {
                    "company": "TCS Ninja",
                    "profile_offered": "Assistant Systems Engineer",
                    "Package(LPA)": 3.36,
                    "CSE": 40,
                    "IT": 0,
                    "ECE": 11,
                    "EEE": 0,
                    "Mech": 2,
                    "Civil": 0,
                    "BIO": 0,
                    "total_no_of_selections": 53
                },
                {
                    "company": "ValueLabs",
                    "profile_offered": "SDET/SDE",
                    "Package(LPA)": 5,
                    "CSE": 1,
                    "IT": 0,
                    "ECE": 1,
                    "EEE": 0,
                    "Mech": 0,
                    "Civil": 0,
                    "BIO": 0,
                    "total_no_of_selections": 2
                },
                {
                    "company": "Incture",
                    "profile_offered": "Trainee (Associate Software Engineer)",
                    "Package(LPA)": 6,
                    "CSE": 4,
                    "IT": 0,
                    "ECE": 0,
                    "EEE": -1,
                    "Mech": -1,
                    "Civil": -1,
                    "BIO": -1,
                    "total_no_of_selections": 4
                }
            ],
            [
                {
                    "company": "Deloitte",
                    "profile_offered": 0,
                    "Package(LPA)": "7.6",
                    "CST": "0",
                    "CFIS": "0",
                    "DS": "0",
                    "VSLI": -1,
                    "PSA": -1,
                    "MD": -1,
                    "MTA": -1,
                    "no_of_selections": "0"
                },
                {
                    "company": "TCS Digital via Digital",
                    "profile_offered": "Systems Engineer",
                    "Package(LPA)": "7",
                    "CST": "0",
                    "CFIS": "0",
                    "DS": "1",
                    "VSLI": "0",
                    "PSA": "0",
                    "MD": "0",
                    "MTA": "0",
                    "no_of_selections": "1"
                },
                {
                    "company": "TCS Ninja via Digital",
                    "profile_offered": "Assistant Systems Engineer",
                    "Package(LPA)": "3.36",
                    "CST": "0",
                    "CFIS": "0",
                    "DS": "0",
                    "VSLI": "0",
                    "PSA": "0",
                    "MD": "0",
                    "MTA": "0",
                    "no_of_selections": "0"
                },
                {
                    "company": "Apisero",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": "5.1",
                    "CST": "0",
                    "CFIS": "0",
                    "DS": "0",
                    "VSLI": "0",
                    "PSA": "0",
                    "MD": -1,
                    "MTA": -1,
                    "no_of_selections": "0"
                },
                {
                    "company": "Accenture - ASE",
                    "profile_offered": "ASE",
                    "Package(LPA)": "4.5",
                    "CST": "0",
                    "CFIS": "0",
                    "DS": "0",
                    "VSLI": -1,
                    "PSA": -1,
                    "MD": -1,
                    "MTA": -1,
                    "no_of_selections": "0"
                },
                {
                    "company": "Accenture - Advanced ASE",
                    "profile_offered": "Advanced ASE",
                    "Package(LPA)": "6.5",
                    "CST": "0",
                    "CFIS": "0",
                    "DS": "0",
                    "VSLI": -1,
                    "PSA": -1,
                    "MD": -1,
                    "MTA": -1,
                    "no_of_selections": "0"
                },
                {
                    "company": "Josh Technology Group",
                    "profile_offered": "Software Engineer (Web/Mobile Technologies)",
                    "Package(LPA)": "9.8",
                    "CST": "0",
                    "CFIS": "0",
                    "DS": "0",
                    "VSLI": -1,
                    "PSA": -1,
                    "MD": -1,
                    "MTA": -1,
                    "no_of_selections": "0"
                },
                {
                    "company": "Cognizant GenC Next",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": "6.5",
                    "CST": "0",
                    "CFIS": "0",
                    "DS": "0",
                    "VSLI": -1,
                    "PSA": -1,
                    "MD": -1,
                    "MTA": -1,
                    "no_of_selections": "0"
                },
                {
                    "company": "Infoview Systems",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": "3.5",
                    "CST": "0",
                    "CFIS": "0",
                    "DS": "0",
                    "VSLI": -1,
                    "PSA": -1,
                    "MD": -1,
                    "MTA": -1,
                    "no_of_selections": "0"
                },
                {
                    "company": "Cognizant GenC",
                    "profile_offered": "Software Engineer",
                    "Package(LPA)": "4",
                    "CST": "0",
                    "CFIS": "1",
                    "DS": "3",
                    "VSLI": -1,
                    "PSA": -1,
                    "MD": -1,
                    "MTA": -1,
                    "no_of_selections": "4"
                }
            ]
        ]
    }
}
const companyResult = JSON.parse(JSON.stringify(result))

export default companyResult