
    const result = {
       vskp : {
         GIT : [
          {
             is_ug : true,
             under_institute_name :  "GIT" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "GIT" ,
             under_campus_name : "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ],
         GIM : [
          {
             is_ug : true,
             under_institute_name :  "GIM" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "GIM",
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ],
         GIS : [
          {
             is_ug : true,
             under_institute_name :  "GIS" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "GIS" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ],
         GSoA : [
          {
             is_ug : true,
             under_institute_name :  "GSoA" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name : "GSoA" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ],
         GIN : [
          {
             is_ug : true,
             under_institute_name : "GIN",
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "GIN" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ],
         GIP : [
          {
             is_ug : true,
             under_institute_name :  "GIP" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "GIP" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ],
         GSoL : [
          {
             is_ug : true,
             under_institute_name :  "GSoL" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "GSoL" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ],
         GSGS : [
          {
             is_ug : true,
             under_institute_name :  "GSGS" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "GSGS" ,
             under_campus_name :  "vskp" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ]
      },
       hyd : {
         GST : [
          {
             is_ug : true,
             under_institute_name :  "GIT" ,
             under_campus_name :  "hyd" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "GIT" ,
             under_campus_name :  "hyd" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ],
         HBS : [
          {
             is_ug : true,
             under_institute_name :  "HSB" ,
             under_campus_name :  "hyd" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "HSB" ,
             under_campus_name : "hyd" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ],
         SoP : [
          {
             is_ug : true,
             under_institute_name :  "SoP" ,
             under_campus_name :  "hyd" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "SoP" ,
             under_campus_name :  "hyd" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ],
         SoS : [
          {
             is_ug : true,
             under_institute_name :  "SoS" ,
             under_campus_name :  "hyd" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "SoS" ,
             under_campus_name :  "hyd" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ]
      },
       blr : {
         GST : [
          {
             is_ug : true,
             under_institute_name :  "GST" ,
             under_campus_name :  "blr" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "GST" ,
             under_campus_name :  "blr" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ],
         SoS : [
          {
             is_ug : true,
             under_institute_name :  "SoS" ,
             under_campus_name :  "blr" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "SoS" ,
             under_campus_name :  "blr" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ],
         GSBB : [
          {
             is_ug : true,
             under_institute_name :  "GSBB" ,
             under_campus_name : "blr" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          },
          {
             is_ug : false,
             under_institute_name :  "GSBB" ,
             under_campus_name :  "blr" ,
             total_students : 100,
             total_final_years : 50,
             total_higher_study_and_pay_crt : 20,
             total_not_intrested_in_placments : 30,
             total_backlogs : 10,
             total_students_eligible : 10,
             total_offers : 18,
             total_multiple_offers : 18,
             total_placed : 9,
             total_yet_to_place : 1,
             highest_salary :  20.00 ,
             average_salary :  7.00 ,
             lowest_salary :  1.20 
          }
        ]
      }
    }
export default result